[package]
name = "miau"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = {version = "0.17", features=["spirv"] }
winit = "0.28"
tokio = { version = "1", features=["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
spirv-builder = "0.9"
