[package]
name = "game_shaders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = "0.9"
miau_shared = { path = "../../miau/shared" }
game_shared = { path = "../shared" }
